version: '3.0'

services:
    api:
        build: .
        environment:
            NODE_ENV: development
            DB_HOST: postgres
            DB_PORT: 5432
            DB_NAME: postgres
            DB_USERNAME: postgres
            DB_PASSWORD: postgres
            SQS_RP_URL: https://sqs.us-east-1.amazonaws.com/962368660083/email
            AWS_DEFAULT_REGION: us-east-1
            AWS_ACCESS_KEY_ID: 'your AWS_ACCESS_KEY_ID'
            AWS_SECRET_ACCESS_KEY: 'you AWS_SECRET_ACCESS_KEY'

        ports:
            - 3000:3000
        volumes:
            - ./src:/app/src
        networks:
            - default

    docs:
        image: swaggerapi/swagger-ui:latest
        environment:
            API_URL: http://localhost:3000/swagger.json
        ports:
            - 3001:8080

    postgres:
        image: postgres:latest
        environment:
            POSTGRES_PASSWORD: postgres
        ports:
            # debugging purposes only, you may change it if its conflicting
            - 5432:5432
        volumes:
            - db-data:/var/lib/postgresql/data

volumes:
    db-data:

